language: go

go:
  - master

install:
  - go get github.com/inconshreveable/mousetrap

before_deploy:
  - "./build.sh $TRAVIS_BRANCH"

deploy:
  provider: releases
  api_key: $GH_API_TOKEN
  file: build/$TRAVIS_BRANCH/*
  skip_cleanup: true
  on:
    tags: true

# branches:
#   only:
#   - /add-travis-ci/

# script:
#   - bash build.sh v-test